### ISSUE TITLE
Do I need to install the knative eventing module?

### ISSUE THREAD

**Issue by JulieLily** [beemarie/async-component#25]
I think it is based on the event redis source, so do I have to install the knative eventing module?

**Comment by JulieLily** [comment]
Can event redis source be replaced with our own redis service?

**Comment by JulieLily** [comment]
@beemarie

**Comment by bvennam** [comment]
Hey @JulieLily thanks for reaching out - This component is being actively developed at the knative-sandbox repo from now on: https://github.com/knative-sandbox/async-component

Please note that it's not really ready for use yet as it's still under development. 🚀 

That said -- yes, you do need knative eventing. The first step in the README says to install knative serving & eventing. You might have to tweak some things, but you should be able to plug in your own redis service.  Please feel free to open up issues at the knative-sandbox repo.

Thanks!
